// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT3_-IWdKlT-fQ7Oe7xESPT7yAcOBBhoY',
    appId: '1:326716042463:web:5e2e8611dab8e6fefa8d6a',
    messagingSenderId: '326716042463',
    projectId: 'sazedar-b526f',
    authDomain: 'sazedar-b526f.firebaseapp.com',
    storageBucket: 'sazedar-b526f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjdjt92vcVODnJMoAZJD8FLhee9wyDfuw',
    appId: '1:326716042463:android:83d8147275cfceb9fa8d6a',
    messagingSenderId: '326716042463',
    projectId: 'sazedar-b526f',
    storageBucket: 'sazedar-b526f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAegPuNWdjz8QOhFwqmnDjhnU5X_iEEOAg',
    appId: '1:326716042463:ios:cc04e0685ed70e3efa8d6a',
    messagingSenderId: '326716042463',
    projectId: 'sazedar-b526f',
    storageBucket: 'sazedar-b526f.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
